const qSelectors = {
    startingIndex : document.querySelector("#startingIndex"),
    game : document.querySelector("#game"),
    // rules : document.querySelector("#rules"),
    // titre : document.querySelector(".imageIndexPerso"),
    // titreDisplay : window.getComputedStyle(document.querySelector(".imageIndexPerso")).getPropertyValue('display'),
    // regle : document.querySelector(".indexRules"),
    // regleDisplay : window.getComputedStyle(document.querySelector(".indexRules")).getPropertyValue('display'),
    dplImageGlobal : document.querySelector("#container"),
    // restart: document.querySelector('#restart'),
    fondJeux : document.querySelector("#fond"),
    items:document.querySelector("#itemsCompetences"),
    couleurOiseau : document.querySelector("#containerOiseau"),
    couleurOiseau2 : document.querySelector("#containerOiseau2"),
    // compteurDePoints : document.querySelector("#compteurDePoints"),
    endGame : document.querySelector("#endGame"),
    // itemsCompetences : document.querySelector("#itemsCompetences"),
    restart : document.querySelector("#restart"),
    dplImageChaudron : document.querySelector("#imageChaudron"),
    dplImageGlobalChaudron :document.querySelector("#containerChaudron"),
    dplImageOiseau : document.querySelector("#imageOiseau"),
    dplImageOiseau2 : document.querySelector("#imageOiseau2"),
    dplImage : document.querySelector("#image"),
    dplImageGlobalOiseau : document.querySelector("#containerOiseau"),
    dplImageGlobalOiseau2 : document.querySelector("#containerOiseau2"),
    compteurDePoints : document.querySelector("#compteurDePointsRestant"),
    compteurDePointsRestant : document.querySelector("#compteurDePoints"),
    itemsCompetences : document.querySelector("#itemsCompetences"),
    javaScript : document.querySelector("#javaScript"),
    typeScript : document.querySelector("#typeScript"),
    html : document.querySelector("#html"),
    css : document.querySelector("#css"),
    angular : document.querySelector("#angular"),
    nodeJs : document.querySelector("#nodeJs"),
    jQuery : document.querySelector("#jQuery"),
    git : document.querySelector("#git"),
    mongoDB:document.querySelector("#mongoDB"),
    json:document.querySelector("#json"),
    vueJS:document.querySelector("#vueJS"),
    react:document.querySelector("#react"),
    titreCompetences:document.querySelector("#titreCompetences"),
    containerToBeContinue : document.querySelector("#containerToBeContinue"),
    containerToBeContinue2 : document.querySelector("#containerToBeContinue2"),
    buttonIndex2 :document.querySelector("#buttonIndex2")
  }

  export default qSelectors;